#!/bin/sh
DEFAULT_S3_BUCKET="s3://autobuilder-artifacts/test-distro"

if ! $(return >/dev/null 2>&1); then
    echo "This script must be sourced" >&2
    exit 1
fi

if [ ! -d "$BUILDDIR/.local/bin" ]; then
    # No local bin dir, see if we need it
    buildenv-host-gcc-check
    if [ -d "$BUILDDIR/.local/bin" ]; then
	PATH="$BUILDDIR/.local/bin:$PATH"
    fi
else
    # We have local bin dir, re-check the symlinks there
    PATH="$BUILDDIR/.local/bin:$PATH"
    buildenv-host-gcc-check
fi

# S3 bucket for mirror storage
#
#  Downloads mirror assumed to be at ${TD_S3_BUCKET}/downloads
#  sstate mirror assumed to be at ${TD_S3_BUCKET}/sstate_mirror
#
#  One should have the `boto3` and `s3transfer` Python packages
#  installed for the host Python3.
#
if [ -z "$TD_S3_BUCKET" ]; then
    if aws s3 ls $DEFAULT_S3_BUCKET >/dev/null 2>&1; then
	echo "Using $DEFAULT_S3_BUCKET for S3 mirrors"
	TD_S3_BUCKET="$DEFAULT_S3_BUCKET"
    fi
fi
if [ -n "$TD_S3_BUCKET" ]; then
    sed -i -e"/@TD_S3_MIRRORS@/c \SOURCE_MIRROR_URL ?= \"${TD_S3_BUCKET}/downloads\"\
OE_IMPORTS += \"oeaws.botos3fetcher\"\
INHERIT += \"own-mirrors\"\
SSTATE_MIRRORS ?= \"file://.* ${TD_S3_BUCKET}/sstate_mirror/PATH;downloadfilename=PATH\"" \
	"$BUILDDIR/conf/local.conf"
fi
